### ISSUE TITLE
ie10 抽奖按钮上部边框穿透背景

### ISSUE THREAD

**Issue by chenxingyu350128** [hengshanMWC/dial-sudoku#1]
![image](https://user-images.githubusercontent.com/20367454/111951461-ab0d7e00-8b1e-11eb-87fb-9f32a25fdc79.png)
![image](https://user-images.githubusercontent.com/20367454/111951515-bcef2100-8b1e-11eb-9914-860ac7eb0ecb.png)

**Comment by hengshanMWC** [comment]
有线上链接吗？我可以方便看看嘛
